WX_INCLUDE = /c/Darek/app/wxWidgets/include/


all:
	g++ main.cpp main.h simple.cpp simple.h QuickThoughtsMain.cpp QuickThoughtsMain.h `wx-config --cxxflags --libs` -o simple -I$(WX_INCLUDE) -I../gfx

